version: '3'
services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}  
      JWT_SECRET: ${JWT_SECRET}  
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
